### ISSUE TITLE
Update bug?

### ISSUE THREAD

**Issue by kicsirigo** [CS2-OOF-LV/CS2Installer#5]
Hello! I got the game from another source, deleted it, but when i try to press enter to update, nothing happens! any fix for that? thanks!

**Comment by NeXiDE** [comment]
Can you please screenshot the Window before pressing enter so we can get more information?

**Comment by kicsirigo** [comment]
I don't know what happeded, but i tried to start the "CS2Installer.exe", pressed enter, the application closed, i opened again, and now its downloading!
